### ISSUE TITLE
Add link to Android app

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#113]
Update the play store icons to no longer be "coming soon" and to link to https://play.google.com/store/apps/details?id=io.verida.vault

There is one on:
* https://developers.verida.io/
* https://developers.verida.io/docs/intro

**Comment by cmcWebCode40** [comment]
@nick-verida,  do you know if we have a google play store icon on Figma without the `coming soon` tag?

**Comment by nick-verida** [comment]
Have asked excited for a new one

**Comment by nick-verida** [comment]
Hey this doesn't seem to have worked. 

I'm testing on `develop` and there is no link.  I checked and `src/constant/index.js` does have the correct link there but the source code generated doesn't include it. See screenshot.

![image](https://user-images.githubusercontent.com/87622993/187578348-8a95b5d4-29a0-44b9-8f85-ca7f84e43c0e.png)
