### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by ysam21** [verida/documentation#121]
Fix typos for "synchronization"

On https://developers.verida.io/docs/concepts/data-sharing

- [x] "Once off data syncronization" should be "Once off data synchronization"

On https://developers.verida.io/docs/concepts/data-storage#data-synchronisation

- [x] "Data synchronisation" should be "Data synchronization"
- [x] "using the CouchDB syncronization protocol" should be "using the CouchDB synchronization protocol"

On https://developers.verida.io/docs/single-sign-on-sdk

- [x] "This private key is used to generated a Decentralized Identity" should be "This private key is used to generate a Decentralized Identity"

**Comment by aurelticot** [comment]
Closed by #132
