### ISSUE TITLE
Change references to SSO to "Verida Connect"

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#124]
We need to change all references from SSO to "Verida Connect"

The pages that need modifying include at least:
* https://developers.verida.io/docs/tutorial/SSO
* https://developers.verida.io/docs/single-sign-on-sdk (change to "Verida Connect SDK")
* https://developers.verida.io/docs/single-sign-on-sdk/how-to-use-the-sso-sdk
* https://developers.verida.io/docs/single-sign-on-sdk/the-sso-authentication-server
* https://developers.verida.io/docs/capabilities
* https://developers.verida.io/docs/glossary

**Comment by cmcWebCode40** [comment]
@nick, 

I have updated all text references from SSO -> Verida Connect.

One question .
Will I have to change the link name as well?
 though this change may cause broken links between pages.

**Comment by nick-verida** [comment]
No don't change that - I think it's fine to keep them like that.
