### ISSUE TITLE
Add metadata to landing page

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#17]
Add HTML metadata to landing page. Use https://www.heymeta.com/url/developers.verida.io to generate correct tags.

**Comment by cmcWebCode40** [comment]
@nick-verida, 

The page you suggested I use to generate the  metadata is broken 

screenshot :
<img width="823" alt="Screenshot 2022-01-24 at 13 09 29" src="https://user-images.githubusercontent.com/54280620/150780600-f4641e51-90a3-4be7-abaa-ff999614c700.png">

Should I search for another helpful site that could help generate meta tags?

**Comment by nick-verida** [comment]
ha wow. Yeah use something else - that was just what @ryank000 was checking it with.
