### ISSUE TITLE
Final updates to docs to complete

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#3]
Here's a list of things that need fixing before we can close this project out:

- The HTML title tag is wrong. It should be getting set from `config.title` in `docusaurus.config.js` but is instead is _Hello from ${siteConfig.title}_
- The HTML description meta tags are wrong. Currently are `<meta name="description" content="Description will go into a meta tag in <head />" data-react-helmet="true">` and `<meta property="og:description" content="Description will go into a meta tag in <head />" data-react-helmet="true">`. Chris asked for the SEO tags to be done and this is one of the main ones. 
- Search doesn't seem to be working. Note that we are going to need to change the URL this is hosted at so we will need to config for this. 
- Please update the link title in the header that goes to https://verida.io. Currently it is titled "Main" and please change that to "Verida Homepage". 
- There are some Markdown-style links that are not being rendered properly. An example is https://main.d3e62gra73ggnc.amplifyapp.com/docs/client-sdk/data#user-owned-datastore where it looks like this:
![image](https://user-images.githubusercontent.com/87622993/146693530-f359762b-8a78-4c63-ac33-c6469ebf3862.png)
Is there a config setting to change this? Or is there a way to find all the cases where this is happening?

**Comment by mykoleg** [comment]
- The HTML title tag is wrong - done
- The HTML description meta tags are wrong - I just added placeholders to all pages for SEO. I think the content of it best may do some SEO expert. I may put something on my own but not sure that it will be correct.
- Search doesn't seem to be working - currently, the ball is on Algolia side, see below:
Around 7 days ago I got this from Algolia:
![image](https://user-images.githubusercontent.com/65669971/146729201-a2112d6b-4950-4e28-a057-08c0ffdb28bf.png)
After that, we make the directory public and I apply one more time (around 5 days ago):
![image](https://user-images.githubusercontent.com/65669971/146729063-3dc70125-4093-4049-9438-8004497decb5.png)
Long time without answer, so I write one more time to them (around 3 days ago):
![image](https://user-images.githubusercontent.com/65669971/146729132-37c983ad-fe6d-4f00-87d8-3ba326bf17ab.png)
I will update you once get an answer from them. No problem with changing URL after.
- Please update the link title in the header that goes to https://verida.io - done
- There are some Markdown-style links that are not being rendered properly - done and checked all places in the code, was only this one 
Is there any channels ok for you that we may use to increase our answer time (Skype, Slack, Telegram, WhatsApp, ...)?

**Comment by nick-verida** [comment]
Thanks @mykoleg 

I've fixed the search by switching to a local search plugin which seems to work. Can you let us know if Algolia gets back to you because I think that would be better though. 

The rest of you changes are good. 

I'll get @tahpot to do a final run through of the site and then I think we are done.

**Comment by mykoleg** [comment]
Local search was one of the options. 
Still no answer from Algolia. Sent them another message:

![image](https://user-images.githubusercontent.com/65669971/147051214-409c1da3-5bb8-4711-83d1-a9efc4e0aa9e.png)

Will write to you once have an answer.
