### ISSUE TITLE
VC example doesn't show in Vault Data

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#62]
Using the VC Example feature branch at https://feature-vc-example.d3e62gra73ggnc.amplifyapp.com/docs/tutorial/verifiable_credentials

Send yourself a VC. It appears as a message correctly and can be accepted, but never appears in the Data section in the Vault

**Comment by pkhien95** [comment]
Fixed in https://github.com/verida/documentation/pull/63

**Comment by nick-verida** [comment]
Fixed
